version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/actions/setup-rust-native"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
