/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImageRouteImport } from './routes/image'
import { Route as PageRouteRouteImport } from './routes/page/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageSettingsRouteImport } from './routes/page/settings'

const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRouteRoute = PageRouteRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSettingsRoute = PageSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PageRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page': typeof PageRouteRouteWithChildren
  '/image': typeof ImageRoute
  '/page/settings': typeof PageSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page': typeof PageRouteRouteWithChildren
  '/image': typeof ImageRoute
  '/page/settings': typeof PageSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/page': typeof PageRouteRouteWithChildren
  '/image': typeof ImageRoute
  '/page/settings': typeof PageSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page' | '/image' | '/page/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page' | '/image' | '/page/settings'
  id: '__root__' | '/' | '/page' | '/image' | '/page/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRouteRoute: typeof PageRouteRouteWithChildren
  ImageRoute: typeof ImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page': {
      id: '/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof PageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/settings': {
      id: '/page/settings'
      path: '/settings'
      fullPath: '/page/settings'
      preLoaderRoute: typeof PageSettingsRouteImport
      parentRoute: typeof PageRouteRoute
    }
  }
}

interface PageRouteRouteChildren {
  PageSettingsRoute: typeof PageSettingsRoute
}

const PageRouteRouteChildren: PageRouteRouteChildren = {
  PageSettingsRoute: PageSettingsRoute,
}

const PageRouteRouteWithChildren = PageRouteRoute._addFileChildren(
  PageRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRouteRoute: PageRouteRouteWithChildren,
  ImageRoute: ImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
